image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

build:
  stage: build
  script:
      - "dotnet build"

test:
  stage: test
  variables:
    RabbitMQ__HOST: "rabbitmq"
  services:
  - name: ${CI_REGISTRY}/infrastructure/rabbitmq:3.8-management-alpine-delayed-latest
    alias: rabbitmq
    
  script: 
      - "dotnet test"
