image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

build:
  stage: build
  script:
      - "dotnet build"

test:
  stage: test
  variables:
    RabbitMQ__Host: "rabbitmq"
    ElasticSearch__Host: "elasticsearch"

  services:
  - name: ${CI_REGISTRY}/infrastructure/rabbitmq:3.8-management-alpine-delayed-latest
    alias: rabbitmq
  services:
  - name: elasticsearch:7.6.2
    alias: elasticsearch
    command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]
    
  script: 
      - "dotnet test"
