# Docker compose file for developers to run the necessary background services.
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "127.0.0.1:5000:80"
      - "127.0.0.1:2525:25"

volumes:
  rabbitmq_data:
  elasticsearch_data:
