apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "redis" "redis.fullname" }}
  labels:
    {{- include "middlemail.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
