name: middlemail
icon: https://always-icecream.com/generated/static-images/miacademy/shared/aki/aki_small.png
apiVersion: v2
description: Transactional Email
type: application

version: 1.0.0
appVersion: 0.3.0

dependencies:
  - name: rabbitmq
    version: "~7.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.provision
  - name: elasticsearch
    version: "~12.3.5"
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.provision
  - name: redis
    version: "~10.7.2"
    repository: https://charts.bitnami.com/bitnami
