name: "CI with dependencies from helm chart"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.4.0
    - name: Create secrets
      run: |
        kubectl create secret generic middlemail-rabbitmq \
          --from-literal=rabbitmq-erlang-cookie=cookie \
          --from-literal=rabbitmq-password=password
    - name: Setup MiddleMail dependencies in k8s
      run: |
        cd helm/middlemail
        helm dependency update
        helm install middlemail . \
          --set rabbitmq.auth.existingErlangSecret=middlemail-rabbitmq \
          --set rabbitmq.auth.existingPasswordSecret=middlemail-rabbitmq \
          --set redis.cluster.enabled=false \
          --set redis.existingSecret=middlemail-redis \
          --set replicaCount=0 \
          --set elasticsearch.master.replicas=1 \
          --set elasticsearch.coordinating.replicas=1 \
          --set elasticsearch.data.replicas=1 \
          --wait
        kubectl cluster-info
        kubectl get pods -o wide
    - name: Forward k8s services
      run: |
        kubectl port-forward svc/middlemail-elasticsearch-master 9200:9200 2>&1 &
        kubectl port-forward svc/middlemail-rabbitmq 5672:5672 2>&1 &
        kubectl port-forward svc/middlemail-rabbitmq 15672:15672 2>&1 &
        kubectl port-forward svc/middlemail-redis-master 6379:6379 2>&1 &
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      env:
        ElasticSearch__Host: "localhost"
        RabbitMQ__Host: "localhost;username=user;password=password"
