name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.4.0
    - name: Setup MiddleMail dependencies in k8s
      run: |
        cd helm/middlemail
        helm dependency update
        helm install middlemail . \
          --set rabbitmq.auth.existingErlangSecret=middlemail-rabbitmq \
          --set rabbitmq.auth.existingPasswordSecret=middlemail-rabbitmq \
          --set redis.cluster.enabled=false \
          --set redis.existingSecret=middlemail-redis \
          --set image.repository=busybox \
          --set image.tag=latest \
          --set elasticsearch.master.replicas=1 \
          --set elasticsearch.coordinating.replicas=1 \
          --set elasticsearch.data.replicas=1 \
          --timeout 600 \
          --wait
        kubectl get pods -o wide
